name: "trade-assembly"
description: "Sample assembly file"

labels:
  user: "ian" 


tables:
  trade:
    description: Trade data
    type: partitioned
    blockSize: 10000
    prtnCol: timestamp
    sortColsOrd: sym
    sortColsDisk: sym
    columns:
      - name: timestamp
        description: Time
        type: timestamp    
      - name: sym
        description: Symbol name
        type: symbol
        attrMem: grouped
        attrDisk: parted
        attrOrd: parted
      - name: price
        description: Price
        type: float    
      - name: size
        description: Size
        type: long      

  quote:
    description: Quote data
    type: partitioned
    blockSize: 10000
    prtnCol: timestamp
    sortColsOrd: sym
    sortColsDisk: sym
    columns:
      - name: timestamp
        description: Time
        type: timestamp    
      - name: sym
        description: Symbol name
        type: symbol
        attrMem: grouped
        attrDisk: parted
        attrOrd: parted
      - name: bid
        description: bid price
        type: float    
      - name: ask
        description: bid price
        type: float   
      - name: bsize
        description: bid price
        type: long  
      - name: asize
        description: bid price
        type: long                  


bus:
  stream:
    protocol: custom
    nodes: tp:5010
    topic: dataStream

mounts:
  rdb:
    type: stream
    baseURI: file:///mnt/foo/i/
    partition: none
  idb:
    type: local
    baseURI: file:///data/db/idb
    partition: ordinal
  hdb:
    type: local
    partition: date
    baseURI: file:///data/db/hdb


elements:
  rc:
    host: sgrc 
    port: 5060 
  sm:
    description: Storage manager
    source: stream      # bus configuration
    tiers:
      - name: mem
        mount: rdb
      - name: intra
        mount: idb
        schedule:
          freq: 0D00:10:00 # every 10 minutes
      - name: hist1
        mount: hdb
        schedule:
          freq: 1D00:00:00 # every day
          snap:   00:00:00 
      #   retain:
      #     time: 2 days
      #     rows: 200000
      # - name: hist2
      #   mount: hdb
      #   store: file:///data/db/hdbtier2/
      #   retain:
      #     time: 5 weeks
      #     size: 2 TB
      #     rows: 10000000

  dap:
    smEndpoints: sm:10001
    gwEndpoints: sgrc:5060
    instances:
      RDB:
        mountName: rdb
      IDB:
        mountName: idb
      HDB:
        mountName: hdb