version: "3"
#
# Services.
#
services:
  feed:
    image: ${KX_DOCKER_REG}/qce:${QCE_VERSION}
    depends_on:
      - tp    
    environment:
      - KX_KURL_DEBUG_LOG=1
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:debug # Optional
    ports:
      - 127.0.0.1::5009
    command: /opt/kx/cfg/proc/feed.q -p 5009 
    volumes:
      - ${HOME}/.qp.licenses:/opt/kx/lic    
      - ./cfg:/opt/kx/cfg 
    env_file:
      - .env 
    stdin_open: true
    tty: true   

  tp:
    image: ${KX_DOCKER_REG}/qce:${QCE_VERSION}
    environment:
      - KX_KURL_DEBUG_LOG=1
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:debug # Optional
    ports:
      - 127.0.0.1::5010
    command: /opt/kx/cfg/proc/tp.q -p 5010 -logDir /opt/kx/tplog -cfg /opt/kx/cfg
    volumes:
      - ${HOME}/.qp.licenses:/opt/kx/lic    
      - ./tplog:/opt/kx/tplog
      - ./cfg:/opt/kx/cfg 
    env_file:
      - .env 
    stdin_open: true
    tty: true    

  
  #
  # Resource Coordinator -- 1 per assembly.
  #
  sgrc:
    image: ${KX_DOCKER_REG}/kxi-sg-rc:${SG_VERSION}
    environment:
      - KXI_NAME=sg_rc
      - KXI_PORT=5060
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:debug # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - KXI_AUTH_DISABLED=1
    ports:
      - 127.0.0.1::5060
    stdin_open: true
    tty: true 
    env_file:
      - .env     
    volumes: 
      - ${HOME}/.qp.licenses:/opt/kx/lic 
      - ./cfg:/opt/kx/cfg         

  #
  # Aggregator. Note we only have one here, but multiple can be configured.
  #
  sgagg:
    image: ${KX_DOCKER_REG}/kxi-sg-agg:${SG_VERSION}
    environment:
      - KXI_NAME=sg_agg
      - KXI_PORT=5050
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:info # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - KXI_SG_RC_ADDR=sgrc:5060
      - KXI_AUTH_DISABLED=1
    ports:
      - 127.0.0.1::5050
    # Optional: deploy multiple replicas.
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env     
    stdin_open: true
    tty: true 
    volumes: 
      - ${HOME}/.qp.licenses:/opt/kx/lic 
      - ./cfg:/opt/kx/cfg                

  #
  # Gateway.
  #
  sggw:
    image: ${KX_DOCKER_REG}/kxi-sg-gw:${SG_VERSION}
    environment:
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - GATEWAY_QIPC_PORT=5040
      - GATEWAY_HTTP_PORT=8080
      - KXI_AUTH_DISABLED=1
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:trace # Optional      
    ports:
      - 127.0.0.1::5040
      - 127.0.0.1::8080
    # Optional: deploy multiple replicas.
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env     
    stdin_open: true
    tty: true  
    volumes: 
      - ${HOME}/.qp.licenses:/opt/kx/lic 
      - ./cfg:/opt/kx/cfg         

  sm:
  #
  # Storage Manager
  #  
    image: "registry.dl.kx.com/kxi-sm-single:1.1.0"
    depends_on:
      - tp
    environment:
      - KXI_NAME=sm
      - KXI_SC=SM
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
      # - KXI_PORT=10001
      - KXI_LOG_FORMAT=text
    ports:
      - 127.0.0.1::10001
    volumes:
      - ${HOME}/.qp.licenses:/opt/kx/lic    
      - ./data:/data
      - ./tplog:/opt/kx/tplog
      - ./cfg:/opt/kx/cfg 
      - ./s3:/opt/kx/s3
    env_file:
      - .env 
      - .cloud_auth_env  
    stdin_open: true
    tty: true      

  rdb:
  #
  # Realtime Database
  #
    image: ${KX_DOCKER_REG}/kxi-da:${DA_VERSION}
    # command: -p 5080
    environment:
      - KXI_NAME=rdb
      - KXI_SC=RDB
      - KXI_PORT=5080
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:trace # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
      - KXI_CUSTOM_FILE=/opt/kx/cfg/custom.api.q
      - KX_TRACE_OBJSTR=1
      - KX_KURL_DEBUG_LOG=1      
      - KXI_SG_RC_ADDR=sgrc:5060
    ports:
      - 127.0.0.1::5080
    volumes:
      - ${HOME}/.qp.licenses:/opt/kx/lic    
      - ./data:/data
      - ./cfg:/opt/kx/cfg     
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env    
      - .cloud_auth_env         
    stdin_open: true
    tty: true      

  idb:
  #
  # Intraday Database
  #
    image: ${KX_DOCKER_REG}/kxi-da:${DA_VERSION}
    # command: -p 5090
    environment:
      - KXI_NAME=idb
      - KXI_SC=IDB
      - KXI_PORT=5090
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:trace # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - KX_TRACE_OBJSTR=1
      - KX_KURL_DEBUG_LOG=1    
      # - KXI_CUSTOM_FILE=/opt/kx/cfg/custom.api.q  
      - KXI_SG_RC_ADDR=sgrc:5060
    ports:
      - 127.0.0.1::5090
    volumes:
      - ${HOME}/.qp.licenses:/opt/kx/lic    
      - ./data:/data
      - ./cfg:/opt/kx/cfg       
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env  
      - .cloud_auth_env           
    stdin_open: true
    tty: true    

  hdb:
  #
  # Historical Database
  #
    image: ${KX_DOCKER_REG}/kxi-da:${DA_VERSION}
    command: -s 8
    environment:
      - KXI_NAME=hdb
      - KXI_SC=HDB
      - KXI_PORT=5100      
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:trace # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${ASSEMBLY_FILE_YAML}
      - KX_TRACE_OBJSTR=1
      - KX_KURL_DEBUG_LOG=1   
      # - KX_OBJSTR_INVENTORY_FILE=_inventory/all.json.gz
      # - KX_OBJSTR_CACHE_PATH=/opt/kx/cache
      # - KX_S3_CACHE_SIZE=10000
      # - KXI_CUSTOM_FILE=/opt/kx/cfg/custom.api.q      
    ports:
      - 127.0.0.1::5100
    volumes: 
      - ${HOME}/.qp.licenses:/opt/kx/lic 
      - ./cfg:/opt/kx/cfg 
      - ./data:/data
      - ./cache:/opt/kx/cache        
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env 
      - .cloud_auth_env           
    stdin_open: true
    tty: true        