apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  securityContext:
    # 'nobody' user
    fsGroup: 65534
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: kx-data-pvc
        mountPath: /mnt/data       
    tty: true   
    stdin: true       
  restartPolicy: Always
  volumes:
  - name: kx-data-pvc
    persistentVolumeClaim:
      claimName: kx-data   